### PR TITLE
README Frappé fix[🥤]

### PR DESCRIPTION
**Pull request by bakermrad2**
I added an icon to the Frappé section in the README.md file.

### CODE REVIEW

**Comment by nekowinston** [comment]
The 🪴 emoji is our emoji key for Frappé across ~200 repositories:
https://github.com/catppuccin/catppuccin#-palette

**Comment by bakermrad2** [comment]
> The 🪴 emoji is our emoji key for Frappé across ~200 repositories: https://github.com/catppuccin/catppuccin#-palette

Oh, sorry the emoji was not visible for me nether in GitHub nor in VS Code, so I thought nothing was there. Now I can see it in Gmail, but It's still not visible there. Either way, thanks for your time.

**Comment by nekowinston** [comment]
Oh, interesting - seems like it got added in [Unicode 13.0 in 2020](https://emojipedia.org/potted-plant/).

Thanks for being willing to contribute! It just seemed like an odd PR without knowing that the Emoji is broken on your end.

**Comment by andreasgrafen** [comment]
*As a side note:*
I had a similar issue with the 🪵 emoji ([as seen here](https://github.com/catppuccin/catppuccin#-ports-and-more)) not showing up for me at all because for some reason the emoji-font on my machine was broken. Manually updating the font-set fixed it, and I haven't run into any issues since then.

**Comment by bakermrad2** [comment]
> _As a side note:_ I had a similar issue with the 🪵 emoji ([as seen here](https://github.com/catppuccin/catppuccin#-ports-and-more)) not showing up for me at all because for some reason the emoji-font on my machine was broken. Manually updating the font-set fixed it, and I haven't run into any issues since then.

Okay, that you so much, I'll try to update the fonts, maybe that can fix it.

**Pull request closed without merging**
