### PR TITLE
feat: client-side theme re-compilation, togglable italics

### LINKED ISSUE #18: No font options available
Just discovered this theme, and fell in love with the colors. Unfortunately, it changes many text strings to italic by default and there is no way of customizing this behavior:

italic
script2

Some people find italic font in their code attractive. I really dislike it and the lack of options to disable this is keeping me from using this theme. I hate italics. I know I'm not the only one. Some themes such as Gruvbox material or One Dark Pro have options in vscode's settings to disable italics:

gruvbox material
one dark pro

While I'm aware there are ways of disabling italics entirely by tinkering in the innards of the vscode json settings, I believe that having dedicated checkboxes in the UI settings adds a lot to the user experience and would be a welcome change.

### PR DESCRIPTION
**Pull request by nekowinston**
Fixes #18 by adding the Catppuccin extension to the VSCode preference
CleanShot 2022-08-29 at 04 52 11

This required rewriting the theme in TypeScript as well.
A pre-release version is now available on the [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=Catppuccin.catppuccin-vsc), version v2.1.0.

### CODE REVIEW

**Review by ghostx31 — COMMENTED** [review]
I have checked this out. Installed the pre-release from the marketplace and the toggles show up for me in the extension settings. But toggling them do not seem to do anything. Tried to check with rust and golang codes. Is there any step I've missed before this could be made to work?

**Comment by nekowinston** [comment]
Yeah, something is still causing the official Extension to not re-compile, while the Debug build from `dev` works.
I'll have to look into it to figure out why, exactly. 🤔

**Comment by nekowinston** [comment]
converting this to a draft, since the VSIX release needs some work to get right.

**Review by sgoudham — APPROVED** [review]
LGTM! Long time in the backlog but happy that we got it recompiling 🎉

(p.s you are very epic winston)

**Pull request merged**
