### PR TITLE
feat: add color overrides

### PR DESCRIPTION
**Pull request by nekowinston**

### CODE REVIEW

**Comment by nekowinston** [comment]
Considering this again, I should improve the Configuration object so it's closer to nvim's `color_overrides`:
```lua
require("catppuccin").setup {
	color_overrides = {
		all = {
			text = "#ffffff",
		},
		latte = {
			base = "#ff0000",
			mantle = "#242424",
			crust = "#474747",
		},
		frappe = {},
		macchiato = {},
		mocha = {},
	}
}
```

**Review by ghostx31 — APPROVED** [review]
Looks good to me. Nice work!

**Comment by nekowinston** [comment]
I added user config settings validation, sadly it seems that we'll have to point to a remote location for the JSON schema:
https://github.com/Microsoft/vscode/issues/20791#issuecomment-280650458

I couldn't figure out how to do it locally, might be a point for future improvement.

**Comment by nekowinston** [comment]
Just caught an edge case last moment, we need to enforce 6-character hex codes because our current way of adding opacity **expects** to result in an 8-character hex code.
https://github.com/catppuccin/vscode/blob/2073294f49dd8846400622e362c31c93b18cb938/schemas/colorOverrides.schema.json#L28

Likely also up for changes in future, but out of scope for this PR.

**Comment by ghostx31** [comment]
Thank you!

**Pull request merged**
