### PR TITLE
feat: active tab highlighting

### PR DESCRIPTION
**Pull request by auchynnikau**
Added active tab highlighting. Closing #44 issue.

Mocha:
image

Macchiato:
image

Frappe:
image

Latte:
image

### CODE REVIEW

**Comment by sgoudham** [comment]
Hi @auchynnikau, could you raise the PR against the Dev branch? As that will contain the latest highlights. 

It makes use of a typescript build system which will auto generate the four flavours based on the colour you provide.

@nekowinston Could you please remind us again of what the build instructions are for the Dev branch?

**Comment by sgoudham** [comment]
Waiting for changes as suggested in this comment: https://github.com/catppuccin/vscode/pull/49#issuecomment-1287988421

**Review by sgoudham — CHANGES_REQUESTED** [review]
Waiting for changes as suggested in this comment: https://github.com/catppuccin/vscode/pull/49#issuecomment-1287988421

**Comment by auchynnikau** [comment]
> Waiting for changes as suggested in this comment: [#49 (comment)](https://github.com/catppuccin/vscode/pull/49#issuecomment-1287988421)

Done

**Review by sgoudham — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
