### PR TITLE
fix(syntax): C# interpolated strings highlighting

### LINKED ISSUE #178: C# Syntax highlighting displays incorrectly for interpolated strings
When accessing a class variable or an object param from within an interpolated string, the entire section should be highlighted as a var, now following the dot, it gets highlighted as a string.

Example:

image

### PR DESCRIPTION
**Pull request by kkrypt0nn**
| Before | After |
|--------|--------|
| before | after | 

- Closes #178

### CODE REVIEW

**Comment by nekowinston** [comment]
Thanks for the PR, is there another scope available though? I try to avoid `meta` when possible.

**Comment by kkrypt0nn** [comment]
The other one could be `variable.other.object.cs` & `variable.other.object.property.cs`, though that'd be everywhere - which isn't that much of an issue I guess
image

**Comment by nekowinston** [comment]
I'm guessing we could also change
https://github.com/catppuccin/vscode/blob/f148b6cb1fef18d759c13ae03b226d8a5bdbb89b/src/theme/tokens/index.ts#L283-L289
to only be `string variable` here? 🤔 
That way, we can probably fix a bunch of interpolation issues without treating C# as a special case.

**Comment by kkrypt0nn** [comment]
Yeah could work as well, up to you - in the end the result is the same, just one you're sure that it won't affect other languages.

**Comment by nekowinston** [comment]
I'll merge this as-is, we can always refactor it later. 🙂

**Review by nekowinston — APPROVED** [review]

**Pull request merged**
